@PagueMais_HostAddress = http://localhost:5151

###Mostrar Todos os Clientes
GET {{PagueMais_HostAddress}}/api/v1/clients
Accept: application/json

### Selecionar Cliente pelo ID
GET {{PagueMais_HostAddress}}/api/v1/clients/  ID
Content-Type: application/json

###Adicionar Clientes
POST {{PagueMais_HostAddress}}/api/v1/clients
Content-Type: application/json

{
  "Name": "Teste",
  "Email": "email@email.com",
  "Cpf": "143.133.125-12",
  "Phone": "8499",
  "BirthDate": "2025-05-25T15:30:00Z"
}

###Deletar Clientes
DELETE {{PagueMais_HostAddress}}/api/v1/clients/  ID
Content-Type: application/json

###Editar Clientes
PUT {{PagueMais_HostAddress}}/api/v1/clients/2f135d3f-3357-462e-9d45-f79b9287026a
Content-Type: application/json

{
  "Name": "",
  "Email": "",
  "Cpf": "",
  "Phone": "0",
  "BirthDate": "0001-01-01T12:00:00Z"
}