@PagueMais_HostAddress = http://20.83.146.99:80

###Mostrar Todos os Clientes
GET {{PagueMais_HostAddress}}/api/v1/clients
Accept: application/json

### Selecionar Cliente pelo ID
GET {{PagueMais_HostAddress}}/api/v1/clients/ClientId
Content-Type: application/json

###Adicionar Clientes
POST {{PagueMais_HostAddress}}/api/v1/clients
Content-Type: application/json

{
  "Name": "Rodolfo",
  "Email": "rodolfo@email.com",
  "Cpf": "581.500.190-22",
  "Phone": "849954",
  "BirthDate": "2023-05-25T15:30:00Z"
}

###Deletar Clientes
DELETE {{PagueMais_HostAddress}}/api/v1/clients/ClientID
Content-Type: application/json

###Editar Clientes
PUT {{PagueMais_HostAddress}}/api/v1/clients/ClientId
Content-Type: application/json

{
  "Name": "",
  "Email": "",
  "Cpf": "",
  "Phone": "0",
  "BirthDate": "0001-01-01T12:00:00Z"
}