@PagueMais_HostAddress = http://localhost:5151

###Mostrar Todos os Produtos
GET {{PagueMais_HostAddress}}/api/v1/products
Accept: application/json

### Selecionar Produto pelo ID
GET {{PagueMais_HostAddress}}/api/v1/products/ProducId
Content-Type: application/json

###Adicionar Produtos
POST {{PagueMais_HostAddress}}/api/v1/products
Content-Type: application/json

{
  "name": "Dipirona",
  "price": 2
}

###Deletar Produtos
DELETE {{PagueMais_HostAddress}}/api/v1/products/ProducId
Content-Type: application/json

###Editar Produtos
PUT {{PagueMais_HostAddress}}/api/v1/products/ProducId
Content-Type: application/json

{
  "name": "Paracetamol",
  "price": 5
}