@PagueMais_HostAddress = http://localhost:5151

### Obter Todos os Carrinhos
GET {{PagueMais_HostAddress}}/api/v1/carts

### Criar Carrinho
POST {{PagueMais_HostAddress}}/api/v1/carts
Content-Type: application/json

{
  "productId": "9496ed20-6ba2-4288-94d3-1bbaabd14f47",
  "purchaseId": "2afcba5a-d32b-482d-8f01-790953c1a41e"
}

### Incrementar Quantidade do Produto no Carrinho
GET {{PagueMais_HostAddress}}/api/v1/carts/increment/CartID

### Decrementar Quantidade do Produto no Carrinho
GET {{PagueMais_HostAddress}}/api/v1/carts/decrement/CartID

### Remover Produto do Carrinho
DELETE {{PagueMais_HostAddress}}/api/v1/carts/remove/CartID