@PagueMais_HostAddress = http://localhost:5151

### Obter Todos os Carrinhos
GET {{PagueMais_HostAddress}}/api/v1/carts

### Criar Carrinho
POST {{PagueMais_HostAddress}}/api/v1/carts
Content-Type: application/json

{
  "productId": "412ef2bf-d2a6-4c1c-911d-f56cc3161878",
  "purchaseId": "f26ed91e-8515-40ff-97c5-6e821b2ed7c0"
}

### Incrementar Quantidade do Produto no Carrinho
GET {{PagueMais_HostAddress}}/api/v1/carts/increment/5285a710-a6c0-4857-826c-1257d91c56b0

### Decrementar Quantidade do Produto no Carrinho
GET {{PagueMais_HostAddress}}/api/v1/carts/decrement/CartGUID

### Remover Produto do Carrinho
DELETE GET {{PagueMais_HostAddress}}/api/v1/carts/remove/CartGUID
