@PagueMais_HostAddress = http://localhost:5151

###Mostrar Todas as Purchases
GET {{PagueMais_HostAddress}}/api/v1/purchases
Accept: application/json

### Selecionar Purchase pelo ID
GET {{PagueMais_HostAddress}}/api/v1/purchases/PurchaseId
Content-Type: application/json

###Adicionar Purchase
POST {{PagueMais_HostAddress}}/api/v1/purchases
Content-Type: application/json

{
  "total": 0,
  "clientId": "f2088aab-8954-4889-802e-f4fabc90c19f",
  "paymentMethod": 1
}

###Deletar Purchase
DELETE {{PagueMais_HostAddress}}/api/v1/purchases/PurchaseId
Content-Type: application/json

###Editar Purchase
PUT {{PagueMais_HostAddress}}/api/v1/purchases/PurchaseId
Content-Type: application/json

{
  "total": 2,
  "paymentMethod": 1,
  "status": 2
}